database: hsqldb

server:
  port: 5000

spring:
  # 直接在Spring Data JPA启动时初始化数据Schema
  datasource:
    schema: "classpath:db/${database}/schema.sql"
    data: "classpath:db/${database}/data.sql"
    sql-script-encoding: UTF-8
  # JPA以及Hibernate相关的配置
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
  resources:
    chain:
      compressed: true
      cache: true
    cache:
      period: 86400

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p})}"
  level:
    root: INFO