# 在启动参数中加入--spring.profiles.active=mysql以激活本配置文件
database: mysql

spring:
  datasource:
    url: "jdbc:mysql://xxx:3306/my_db?useUnicode=true&characterEncoding=utf-8"
    username: "root"
    password: "admin"
    initialization-mode: always